### ISSUE TITLE
error while updating the repository with setup.py

### ISSUE THREAD

**Issue by SiNa88** [daffidwilde/matching#62] opened 2019-10-30 10:39 UTC
Hello Henry,

I was installing the updated repository, but I got the following error.
I tried with python 2.7, 3.5, and 3.7. But i received the same error. Can you help me? Thanks

SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/matching/games/hospital_resident.py to hospital_resident.cpython-35.pyc
  File "build/bdist.linux-x86_64/egg/matching/games/hospital_resident.py", line 110
    f"{resident} is matched to {resident.matching} but "
                                                       ^
SyntaxError: invalid syntax

copying src/matching.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/matching.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/matching.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/matching.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    tests_require=["pytest", "numpy"],
  File "/usr/local/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 220, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 273, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 383, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 422, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

**Comment by daffidwilde** [comment] 2019-10-30 11:16
Hi there,

That is a very odd error that I've never seen before. I'd love to help and to make things easier for me, could you clarify which branch/release you were attempting to install from, and the commands you used to do so.

Cheers

**Comment by daffidwilde** [comment] 2019-10-30 12:02
I hadn't noticed that there were in fact two errors here. The first error is because I have opted to use `f`-strings over `%`-formatting or the `str.format` method. `f`-strings are only supported for Python 3.6 and above so that would explain why you are unable to install with 2.7 and 3.5.

However, being unable to install Python 3.7 remains a mystery. I've just added regular support-checking for 3.7 (and 3.8) through Travis (3134247a) so would you be able to uninstall matching and attempt that again?

Having a look around, it would seem that the second error is being caused by a corrupted compiled Python file (`.pyc`). This could be because the same install of `setuptools` is being used by various versions of Python in your base environment.

To remedy that, I would suggest deleting all of the compiled files (they will be replaced as needed) using a command such as `find /usr -name '*.pyc' -delete`

Or to verify that will fix your issue, try deleting the specific file's compiled version and attempting the install again.

For Python 2.7 it should be here:
```
/usr/local/lib/python2.7/site-packages/setuptools/command/bdist_egg.pyc
```

For Python 3.x it should be here:
```
/usr/local/lib/python3.x/site-packages/setuptools/command/__pycache__/bdist_egg.cpython-3x.pyc
```

**Comment by daffidwilde** [comment] 2019-11-06 22:41
Fantastic -- I am glad I could help you out. I'll close this issue now but feel free to reopen it if the problem persists.

**Closed by daffidwilde** 2019-11-06 22:41 UTC
